### ISSUE TITLE
登录表单验证问题

### ISSUE THREAD

**Issue by nerozhang** [2301887641/yunos#1]
后台登录表单验证是引入的YII验证吗？还是bootstrap自带的?

**Comment by 2301887641** [comment]
bootstrap自带的,这个是tp不是yii

**Comment by nerozhang** [comment]
你好，后台登录验证现在不起作用，一点击登录直接就跳转到一个undefined页面

**Comment by 2301887641** [comment]
你好，tp5以后自带的验证码需要使用composer进行安装，请在项目根目录下执行composer install,来安装验证码等核心功能

**Comment by nerozhang** [comment]
已经在根目录下执行composer install，安装依赖已经完成，但是点击登录还是和之前说的一样。有空请帮忙看下吧

**Comment by 2301887641** [comment]
登录需要输入用户名和密码，如果什么都没有输入的话，并没有做限制，所以会跳转到undefined页面
